name: boilerplate_template
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  rename: ^3.0.2
  flutter_localization: ^0.2.2
  intl: ^0.19.0
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  # Riverpod 3.0 moderne avec code generation
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  go_router: ^13.2.0
  google_fonts: ^6.2.1
  country_code_picker_plus: ^0.0.9
  shared_preferences: ^2.3.2
  permission_handler: ^11.3.1
  connectivity_plus: ^6.0.5
  google_sign_in: ^6.2.1
  flutter_dotenv: ^5.2.1
  http: ^1.2.2
  flutter_secure_storage: ^9.2.2
  firebase_crashlytics: ^4.1.3
  firebase_analytics: ^11.3.3
  flutter_local_notifications: ^18.0.1
  firebase_messaging: ^15.1.6
  timezone: ^0.10.0
  # Logger moderne pour remplacer print()
  logger: ^2.4.0
  # Sérialisation moderne
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  # Splash screen natif
  flutter_native_splash: ^2.4.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.11
  test: ^1.25.2
  # Riverpod 3.0 code generation
  riverpod_generator: ^2.6.2
  riverpod_lint: ^2.6.1
  # Sérialisation code generation
  freezed: ^2.5.7
  json_serializable: ^6.8.0


flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/google_logo.png
    - .env

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

# Configuration du splash screen natif
flutter_native_splash:
  # Couleur de fond du splash screen
  color: "#FFFFFF"
  
  # Image du logo au centre
  image: assets/images/logo.png
  
  # Mode sombre (optionnel)
  color_dark: "#1C1B1F"
  image_dark: assets/images/logo.png
  
  # Configuration Android 12+
  android_12:
    image: assets/images/logo.png
    color: "#FFFFFF"
    color_dark: "#1C1B1F"
    icon_background_color: "#FFFFFF"
    icon_background_color_dark: "#1C1B1F"
    android_gravity: center
    ios_content_mode: scaleAspectFit
    web_image_mode: contain
  
  # Plein écran (cache la barre de statut)
  fullscreen: true
